### ISSUE TITLE
"Block this user" option in own profile

### ISSUE THREAD

**Issue by Tanvir-rahman** [utopian-io/utopian.io#11]
#### Expected behavior

Own Profile should not have "Block this user" option in Utopian.io

#### Actual behavior
"Block this user" option is showing in profile section
![1.PNG](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509347577/dbjsne0ugfgb8ms62v4f.png)

#### How to reproduce
1) Go to [Own profile](https://utopian.io/@tanvirrahman) in utopian.io.
2) Click on 3 dot options.

**Comment by eastmaels** [comment]
Fixed in PR #24

**Comment by taylankasap** [comment]
Someone close this issue?

**Comment by azarus** [comment]
Issue can be closed @wehmoen
