### ISSUE TITLE
Search results disappear when scrolling to the bottom

### ISSUE THREAD

**Issue by JefPatat** [utopian-io/utopian.io#12]
#### Expected behavior

When I search for something and I scroll down to the last result the scrolling should stop and I should keep seeing the last results.

#### Actual behavior

Somehow the search results disappear and I end up with a pseude item. Also the scrollbar gets removed because there are now not enough items to further scroll.
![image](https://user-images.githubusercontent.com/13467568/32159960-f41cfa8a-bd4f-11e7-8a36-e56687731901.png)

#### How to reproduce

Search for 'block' in ideas. Scroll to the last result.

* Browser: Opera 48, Chromium engine
* Operating system: Windows 8.1

**Comment by taylankasap** [comment]
Is there a work in progress for this bug? If not I might attend to it. No promises though.

**Comment by azarus** [comment]
Hi @JefPatat i am unable to reproduce this issue, could you elaborate a bit more and provide a step by step explanation how to reproduce this?
Thank you

**Comment by azarus** [comment]
@JefPatat This issue had been closed as the issue can not be reproduced and we didn't get any anwswer from you. If you have the time please provide us with detailed steps to reproduce this and we'll reopen the issue.
Thank you!
