### ISSUE TITLE
Selection box is breaking layout

### ISSUE THREAD

**Issue by Tanvir-rahman** [utopian-io/utopian.io#14]
#### Expected behavior

Selection box should not come out of the layout when scrolling

#### Actual behavior

Selection box is breaking layout while scrolling
![2](https://user-images.githubusercontent.com/15964566/32165344-a580e39a-bd8c-11e7-97ed-0115a58cb64d.png)

#### How to reproduce
1) Go to [utopian.io](https://utopian.io/)
2) Open selection box on top
3) Scroll the page. Scrolling should be done on page / out of the box.

**Comment by azarus** [comment]
This had been fixed.
@wehmoen you may close this issue.
