### ISSUE TITLE
No search option in mobile layout

### ISSUE THREAD

**Issue by Tanvir-rahman** [utopian-io/utopian.io#15]
#### Expected behavior

A search option should be added for mobile device.

#### Actual behavior

There is no search option for mobile device.

![1](https://user-images.githubusercontent.com/15964566/32165547-5697afec-bd8d-11e7-9734-51c35bb408bd.PNG)

#### How to reproduce
1) Go to [utopian.io](https://utopian.io/) with mobile device.

**Comment by taylankasap** [comment]
It looks like this is no longer an issue.

**Comment by azarus** [comment]
@wehmoen you may close this issue
