### ISSUE TITLE
Extra space in top [Mobile layout]

### ISSUE THREAD

**Issue by Tanvir-rahman** [utopian-io/utopian.io#16]
#### Expected behavior

In mobile device there should be no/less extra space [See screenshot].

#### Actual behavior
An extra space is showing in mobile layout
![1](https://user-images.githubusercontent.com/15964566/32165966-9f073184-bd8e-11e7-9781-81b151757cae.png)

#### How to reproduce

1) Go to [utopian.io](https://utopian.io/) from mobile device

**Comment by taylankasap** [comment]
This only happens when you open the page on desktop mode, then change device via devtools. And even then, if you reload the page it works properly.
