### ISSUE TITLE
vote too small

### ISSUE THREAD

**Issue by h4ck3rm1k3** [utopian-io/utopian.io#189]
Sending a %1 vote 
https://utopian.io/utopian-io/@josediccus/suggestion-add-invisible-icon-on-already-made-post-as-an-option-on-steemit-com

I see the trace :
{"operations":[["vote",{"voter":"h4ck3rm1k3st33m","author":"josediccus","permlink":"suggestion-add-invisible-icon-on-already-made-post-as-an-option-on-steemit-com","weight":200}]]}

The return is "Voting weight is too small, please accumulate more voting power or steem power" but it shows error 124
{"error":"server_error","error_description":"10 assert_exception: Assert Exception\nabs_rshares > STEEMIT_VOTE_DUST_THRESHOLD || o.weight == 0: Voting weight is too small, please accumulate more voting power or steem power.\n    {}\n    th_a  steem_evaluator.cpp:1195 do_apply\n\n    {\"o\":{\"voter\":\"h4ck3rm1k3st33m\",\"author\":\"josediccus\",\"permlink\":\"suggestion-add-invisible-icon-on-already-made-post-as-an-option-on-steemit-com\",\"weight\":200}}\n    th_a  steem_evaluator.cpp:1504 do_apply\n\n    {\"op\":[\"vote\",{\"voter\":\"h4ck3rm1k3st33m\",\"author\":\"josediccus\",\"permlink\":\"suggestion-add-invisible-icon-on-already-made-post-as-an-option-on-steemit-com\",\"weight\":200}]}\n    th_a  database.cpp:2892 _apply_transaction\n\n    {\"trx\":{\"ref_block_num\":41548,\"ref_block_prefix\":1478235088,\"expiration\":\"2017-12-02T15:26:39\",\"operations\":[[\"vote\",{\"voter\":\"h4ck3rm1k3st33m\",\"author\":\"josediccus\",\"permlink\":\"suggestion-add-invisible-icon-on-already-made-post-as-an-option-on-steemit-com\",\"weight\":200}]],\"extensions\":[],\"signatures\":[\"X\"]}}\n    th_a  database.cpp:2896 _apply_transaction\n\n    {\"trx\":{\"ref_block_num\":41548,\"ref_block_prefix\":1478235088,\"expiration\":\"2017-12-02T15:26:39\",\"operations\":[[\"vote\",{\"voter\":\"h4ck3rm1k3st33m\",\"author\":\"josediccus\",\"permlink\":\"suggestion-add-invisible-icon-on-already-made-post-as-an-option-on-steemit-com\",\"weight\":200}]],\"extensions\":[],\"signatures\":[\"X\"]}}\n    th_a  database.cpp:660 push_transaction\n\n    {\"call.method\":\"call\",\"call.params\":[\"network_broadcast_api\",\"broadcast_transaction_synchronous\",[{\"ref_block_num\":41548,\"ref_block_prefix\":1478235088,\"expiration\":\"2017-12-02T15:26:39\",\"operations\":[[\"vote\",{\"voter\":\"h4ck3rm1k3st33m\",\"author\":\"josediccus\",\"permlink\":\"suggestion-add-invisible-icon-on-already-made-post-as-an-option-on-steemit-com\",\"weight\":200}]],\"extensions\":[],\"signatures\":[\"X\"]}]]}\n    th_a  websocket_api.cpp:124 on_message"}

**Comment by azarus** [comment]
@h4ck3rm1k3 There is nothing we can do about it. As the error is descriptive you have no enough steem power left to perform the vote. Could you provide a step by step guide how to reproduce this issue?
If the problem was that you had no enough steem power you simoly have to power up. Or just wait until you get your delegated steem back.

Azarus

**Comment by h4ck3rm1k3** [comment]
Hi, this error message is obscure and confusing. So the question is how do you handle this error and display it to the user?

**Comment by azarus** [comment]
Hey, @h4ck3rm1k3 Thanks for getting back quickly. Could you provide with the a screen of the current error message? Is there any error message when you run out of steem power? As in your opening issue you didn't provide enough details it is hard to understand whats the problem. Please also use markdown to properly format your issue.
Thank you

**Comment by h4ck3rm1k3** [comment]
I have reported this months ago, you are getting to me now. I am not even currently using the platform. 
Here is the steem error message 
abs_rshares > STEEMIT_VOTE_DUST_THRESHOLD || o.weight == 0: Voting weight is too small, please accumulate more voting power or steem power.\n {}\n th_a steem_evaluator.cpp:1195

You can see the code here : 
https://github.com/steemit/steem/blob/master/libraries/chain/steem_evaluator.cpp#L1201

The vote weight is basically reduced to 0

You can see here 
https://steemd.com/utopian-io/@josediccus/suggestion-add-invisible-icon-on-already-made-post-as-an-option-on-steemit-com

voter | weight | wgt% | rshares | pct | time
-- | -- | -- | -- | -- | --
h4ck3rm1k3st33m | 0 B |   | 107,923,714 | 11% | 2017-12-02T15:20:57

The weight was zero at 11% so what would it have been at %1?

**Comment by azarus** [comment]
@h4ck3rm1k3 Yes i know the issue is old, and I am very sorry about this. Utopian had limited resources to review the issues before. I am evaluating every issue so we can clean up the ones that are already fixed.

If you have time please let me know if you run into this issue again on utopian. Thank you for your help.

**Comment by h4ck3rm1k3** [comment]
Look, just tell me what your code would do if that assertion would be called? How do you handle steem back end errors? It seems that utopian does not do any error handling. Please reopen.

**Comment by azarus** [comment]
@h4ck3rm1k3 I just checked it, and yes as far as i see there is no error dialog notifying the user about having insufficient voting power. The issue had been closed because it was not clear what is the problem. I've opened a new issue with detailed description here: https://github.com/utopian-io/utopian.io/issues/351
