### ISSUE TITLE
Utopian Drop Down Menu Not Functioning Properly 

### ISSUE THREAD

**Issue by cryptogee** [utopian-io/utopian.io#193]
![Drop down menu.JPG](https://res.cloudinary.com/hpiynhbhq/image/upload/v1512320630/o0nrrcgcngsryoitueif.jpg)

I have found a bug on the Utopian categories drop down menu. The menu should be able to browse categories and then browse particular subjects within those categories.

At the moment if I change a category nothing happens, unless I then type in a word in the search box next to it.

Maybe this was done on purpose, however I feel in order to keep striving to make Utopian as user-friendly as possible, potential new users should be able to browse the categories without having to give a specific subject search.

This will enable potential new contributors who are not that technically minded to search and use the platform.

Solution: each change of category using the drop-down menu should bring up all subjects within that category.

This bug was found using latest version of Google Chrome as of 03/12/2017 and Windows 10 64 bit, fully updated.

[*Cryptogee*](https://steemit.com/@cryptogee)

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@cryptogee/utopian-drop-down-menu-not-functioning-properly">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by alex-osman** [comment]
I am working on this
