### ISSUE TITLE
Requesting to Add resteem features to utopian.io

### ISSUE THREAD

**Issue by ruahtheking** [utopian-io/utopian.io#20]
# Requesting to Add resteem features in utopian.io.
While Reading the newest announcement of founder of **Utopian.io** I have come to think that his post must be resteem and I tried to scroll down and see if theres a resteem button below the post. but sadly there's no resteem there. so I still need to go in Steemit webpage to resteem his post. 

So I go to steemit and resteem his post.
![Capture_2017_10_31_02_53_41_793.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509386133/bcvhsqv6poofbic4s8d2.png)

I right click the resteem feature and copy its code to insert it in utopian.io. just to detailed where we can put it in utopian. 
![Capture_2017_10_31_02_17_34_476.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509386426/jv09obaqihtzyamwmfhf.png)

after copying the codes. I go to Utopian.io and I edit the HTML and added the codes I copied from Steemit.com
![Capture_2017_10_31_02_22_13_9.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509386914/tttj0wew5mkjedpam6du.png)

And finally Successfully added the features. But it needs to program it to properly work so I leave the works to the developers. 
![Capture_2017_10_31_02_22_35_661.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509387187/in51ssbtscslx0olb90j.png)
If we have this features We don't have to go to steemit.com to directly resteem the post. 

<br /><hr/><em>Open Source Contribution posted via <a href="https://utopian.io/utopian-io/@ruah/requesting-to-add-resteem-features-to-utopian-io">Utopian.io</a></em><hr/>

**Comment by azarus** [comment]
@ruahtheking thank you for the feature request, it had been added to the backlog and will be implemented as soon as we have enough resources.

**Comment by diegopucci** [comment]
Resteeming is not part of the utopian concept IMHO. I am closing this issue for now.
