### ISSUE TITLE
Requesting Feature for Improvements in Profile Page of utopian.io

### ISSUE THREAD

**Issue by shreyasgune1** [utopian-io/utopian.io#21]
This has been a terrific week for me. I have really loved exploring the world of open source software development to be able to contribute more effectively to their development through the most amazing model of funding open source software development, i.e. [*utopian.io*](https://utopian.io).

I have explored *Github* and created an account on it. I have dabbled with opening new repositories and had fun in exploring the various *techno* jargon I was hitherto unfamiliar with like forks and branches. I also explored a wonderful platform for deployed apps called *Heroku* which manages all the complex backend services. I managed to deploy various apps by first importing them to my Github repositories and then deploying them through *Heroku*. 

The only reason I could have the courage to proceed so far was *utopian.io* which has been wonderfully supporting my forays into the digital world. @elear and the whole *utopian.io* team has been a source of inspiration for people like me and I can not thank them enough.

Through this post, I would like to request certain changes in the profile page of *utopian.io*.

## The problem

1. This is how my utopian.io profile page looks like:
![Screen Shot 2017-10-30 at 9.24.05 PM.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509380181/bqkxotgmfutxu07vzomv.png)

2. When you click at the three dots near *Edit Profile* page, the menu is visible:
![Screen Shot 2017-10-30 at 9.25.14 PM.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509380280/pygykmmnndq3lj9tglvy.png)

3. This menu has two items *support* and *block the user*. In any world, I should not be having the ability to support and blocking myself!

4. I was curious so I clicked on support, this window pops out:
![Screen Shot 2017-10-30 at 9.25.36 PM.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509380402/gmfsmihqnvuphjr30fst.png)

5. I did not foray more into it, as I thought I may trigger an anomaly. I am not sure what would happen if I transfer funds to myself  !! I believe if I can indeed transfer fund to myself then I could possibly make it go in a loop. If this is indeed possible for my account, I could as well do it for many accounts. Since new accounts would need the only delegation of some SP, I could cheaply open 1000 accounts and put them on self-supporting loop. This could lead to substantially slowing down of blockchain and make all frontends of steem load slowly or even not load at all. It seems like a self-inflicted DDoS to me. I am not really sure that this could happen. But if it could, I request the best minds on the blockchain to stop it !! This problem needs to be tested for the whole blockchain. 

6. The Edit profile button visible on profile page when clicked takes the user back to steemit.com:
![Screen Shot 2017-10-30 at 9.24.53 PM.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509381005/hpu7dkmqwwgfvd05ly5r.png)
I believe *utopian.io* should be self-sufficient in a sense that it does not need to rely on steemit.com for such small things as editing profile info.

7. On the left side, below personal information of the user, there is again a button for support. This doubling of *support* may be avoided and only one support button below the user info may be provided. It is very important that the options to support and block a user are not visible to the user himself.

## The Solution

1. Hide options for supporting and blocking the user for himself. The three dots in one's own profile will not be visible to oneself and nor would be the support button. This is how it would look like:
![Screen Shot 2017-10-30 at 9.24.05 PM.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509382015/iwvakccv9d8iyjfzodeo.png) 

2. Test if self-supporting oneself by transfer for steem to one's own account create anything remotely resembling a DDoS.

**Comment by azarus** [comment]
@shreyasgune1 This had been solved. The issues can be closed thank you.
