### ISSUE TITLE
Pending Review Tab is not getting Highlighted

### ISSUE THREAD

**Issue by codingdefined** [utopian-io/utopian.io#229]
As you can see below when I click on the Pending Review, it's not highlighting that which is done on other tabs like All, Blog Posts. It would be better if we get the highlighted in Pending Review as well.

<a href="https://cl.ly/1r3P0z07020U" target="_blank"><img src="https://dr5mo5s7lqrtc.cloudfront.net/items/1O0v2P0X1O190C3z0x1v/Screen%20recording%202017-12-22%20at%2002.02.58%20PM.gif" style="display: block;height: auto;width: 100%;"/></a>

### Expected Behaviour

It should show the Highlighted lines on Pending Review as well

### OS : Windows 10

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@codingdefined/pending-review-tab-is-not-getting-highlighted">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by alex-osman** [comment]
^^ Please check if this PR fixes this #231

**Comment by codingdefined** [comment]
Now since Pending Review Section is not there, closing this issue.
