### ISSUE TITLE
Github Project Not Automatically Added

### ISSUE THREAD

**Issue by eastmaels** [utopian-io/utopian.io#25]
I have just read the [announcement](https://steemit.com/utopian-io/@elear/utopian-is-unstoppable-now-fully-integrated-with-the-github-project-feeds) from @elear regarding integration with Github project feeds.

So I wanted to try it out. For the impatient, here's a gist of the bug and what I am expecting to happen.

## 1. Expected behavior

Github project field should be automatically inputted after selecting the Github repository on the right.

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509401801/bznkiafkbd3ihd1kbsx4.png)

## 2. Actual behavior

After selecting a repository on the right, clicking "Add contribution", selecting a contribution category, and clicking "I understand. Proceed" it will bring me to a contribution page where the **Github project** field is empty.

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509401986/zlsnxzmokqtoohgaltr5.png)

## 3. Replication Steps

To completely replicate the steps. Here are the steps I made. 

(This author assumes you're already logged into the utopian.io platform)

### 3.1. Synch with Github

<div class="pull-right">

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509402310/wquyq2kdbzhfo94qwilo.png)

</div>

On the right panel of your screen, click on **Synch with Github**. (Actually, I think this should be **Sync** not **Synch**)

***

### 3.2. Authorize utopian.io

<div class="pull-right">

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509402390/s0l3jgvdpjoeyu7rc3zp.png)

</div>

Authorize utopian-io to access your Github account.

***

### 3.3. Select Github repository

<div class="pull-right">

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509402582/hn3lkhnb7wkobrnqalfr.png)

</div>

Select on the Github repository you would like to contribute to. For this example, I wanted to contribute to `eastmaels/smarthome`, so I clicked on that.

***

### 3.4. Click "Add Contribution"

<div class="pull-right">

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509402659/tmww5yonpy1byptrw8mm.png)

</div>

It will bring me to my repository's contribution page. I clicked on "Add Contribution."

***

### 3.5. Select Contribution Category

<div class="pull-right">

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509402742/bgvfp5fjuuvfxulvms3t.png)

</div>

In the project contribution page, select the category you want to contribute. This time I wanted it to be "Development".

***

### 3.6. Read the Rules and Click "I understand. Proceed"

<div class="pull-right">

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509402785/wjkavkqqupnncvlj6bli.png)

</div>

After reading through the rules, I clicked on **"I understand. Proceed"**

***

### 3.7. Result

As mentioned in the beginning of this post, it gave me a blank **Github project**.

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509402843/dqsxo0qhckzxtqtplzhc.png)

When I was expecting it to be populated as this:

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509403259/kpzp6cr4kckxcvpwy3zp.png)

### 4. Others

This is also a test post to use this new feature in utopian.io and see if this will automatically register as an Issue in the utopian.io repository.

</center>

<br /><hr/><em>Open Source Contribution posted via <a href="https://utopian.io/utopian-io/@eastmael/github-project-not-automatically-added">Utopian.io</a></em><hr/>

**Comment by azarus** [comment]
Hi @eastmaels , thank you i was able to reproduce the issue.

Just for tracking purposes and clarification:
@wehmoen i can confirm that clicking on the `Add Contribution.` link does not autofill the repository field. But clicking on the speaker button does pre-fill the repository field.

There is also a related issue i found is that when clicking on the project that had contributions before the:
The old list shows up and there is no way to add contributions.
![](https://i.imgur.com/kN74Yts.png)

Also only task requests can be added:
![](https://i.imgur.com/Sx7mCb1.png)

When clicking on an item

**Comment by diegopucci** [comment]
Closing this as this is a UX thing that will substantially change in the next version
