### ISSUE TITLE
Feature Request: Add the ability to filter the post by secondary tags on Utopian #11

### ISSUE THREAD

**Issue by lykkejay** [utopian-io/utopian.io#26]
## <center>Welcome to my 11th contribution for Utopian and 17th on Utopian platform</center>

Welcome to Utopian if you are new and congratulations to everyone who have joined this parade with us. I am very happy to see that we have surpassed over 1 million steem power delegations. Huge huge thanks to @freedom by doubling the delegation twice. @elear is attending the SteemFest which is happening in Lisbon, Portugal, so I am sure that this will take Utopian to next level. We will be seeing lots and lots of supporters and believers of what Utopian is trying to do. It is going to be a very interesting journey to see where Utopian will reach in even next few months. New to this? Utopian.io is the platform where open source contributors will get rewarded for their work where they were not getting paid anything before. Utopian.io is only the platform where open source contributors get paid as of now. If you are new to this and haven't got the opportunity to learn about Utopian then I suggest you Click on the Icon at the bottom of this page. 
<center>![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509417113/p79evdc2amqekpsmffoc.png)</center>
## <center>My Contribution Today</center>

I am pretty sure we all love to search for posts by tags since we will be able to search for the articles based on our interests. We have been using tags to find new users which interest us or to be found. We have the ability to use up to five tags here on Utopian like in Steemit. When you post from Utopian, you are allowed to add up to 4 tags where Utopian-io will automatically become your main tag. When your post gets submitted, but you will be able to access your post imminently on Steemit.com and it will get to Utopian.io review section on the Utopian platform. You will be able to search your post by tags on Steemit and reach many users with the power of those 5 tags. Your post will get to contribution section after the review process which is normally super fast. So now, the main issue comes...

<center>![](https://steemitimages.com/DQmbUz8UfhfGhTmseScULPYkQgiPdxav3mdWhf1y9BAfFvi/image.png)</center>
How are we going to search the posts by other tags? We are given the ability include up to 5 tags, but suddenly after posting, you will be able to view the posts based on contribution categories. Yes, You can search via search bar on the top, but this is the result, but couldn't search for the tag I was searching for. 
<center>![](https://steemitimages.com/DQmPSYnDFhecG9nDmoMPENfZ3VNrhBRwYT2MhXxkZGBFMhq/image.png)</center>
I was searching for the #busy tag, but the result came up was Utopian-io project. And the weird part is user hasn't even used the #busy tag.
<center>![](https://steemitimages.com/DQmYAhZkqfH2LGhvfD6qftNiZquRw8QsxzHANM9URxoCa3A/image.png)</center>

Above is the screenshot of the tags used by the first user, You can clearly see that he hasn't used the #busy tag. Ok, Since this user has the tags listed here, We might be able to search the posts with this tags, right? Still, the answer is no, you can't search the posts by tags. They are non-responsive. 

## <center> My proposal: Please add the ability to filter the post by secondary tags. </center>

Since we get posts which have used utopian-io tags and approved on our feed, so that gives us many choices and sometimes, we might want to search for posts on certain tags. In my opinion, adding this features in the Utopian will bring great the highest user satisfaction. Users can freely use the secondary tags to look for the contributions that they are most interested about. And also allow the tags on the posts to be searchable when you click the tags on the posts. We can give most used tags as a default option and user to see more ability if he is interested in something else as well.

Thank you very much for reading my contribution. If you have any questions or suggestions then please feel free to comment below. If you would like to contribute to the open source project just like I did with this post then Please click the Utopian Icon below or visit utopian.io
<center> 
**Click [![utopian.io](https://utopian.io/img/utopian-logo-120x120.png)](https://utopian.io)  to Contribute**
Yours @lykkejay 
</center>

<br /><hr/><em>Open Source Contribution posted via <a href="https://utopian.io/utopian-io/@lykkejay/feature-request-add-the-ability-to-filter-the-post-by-secondary-tags-on-utopian-11">Utopian.io</a></em><hr/>

**Comment by azarus** [comment]
@lykkejay thank you for your input. We gona look into adding such an option in the future.

For clarification purposes i re-describe the issue so for future developers can understand the issue easier:

### ACs:
- Keyword with a hashtag prefix should search for tags in contributions.

### Example:
`#busy`
- Should find all contributions with the `busy` tag. Currently there is a bug which also needs to be fixed (mentioned below)


**Note**
@wehmoen I can confirm there is also a related bug:
https://utopian.io/utopian-io/@azarus/utopian-search-keyword-hashtag-is-not-escaped

**Comment by azarus** [comment]
I am closing this as it's already implemented and merged in master.
