### ISSUE TITLE
Bug in utopian moderation control. 

### ISSUE THREAD

**Issue by umair1209** [utopian-io/utopian.io#266]
#### Expected behavior
After the last update in utopian moderation control, moderators can no longer keep the posts pending. 

#### Actual behavior
As a moderator at utopian, I clicked on verify a post option but it I forgot to check some information, so I clicked on the cross option at the right top of tge screen and utopian displayed that "would you like to keep this post pending insread" which is unusual as moderators are not allowed to keep a contribution in pending state. 
#### How to reproduce
The bug can be reproduced by following the below steps. 
- Click verify option 
- Click on cross option at the right top end of the screen
- It will ask you to keep the post pending instead. 
* Browser: Google chrome for android 63.0.3239.111
* Operating system: Android 6.0.1;Redmi 3S BUILD/MMB29M

#### Recording Of The Bug

![20180116_171303.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1516196503/vxialjelh57g4fi53y1e.gif)

    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@syedumair/bug-in-utopian-moderation-control">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by wehmoen** [comment]
Duplicate: https://github.com/utopian-io/utopian.io/issues/261
