### ISSUE TITLE
Consider restoring Busy copyrights

### ISSUE THREAD

**Issue by Sekhmet** [utopian-io/utopian.io#276]
I am one of developers at Busy. This is not legal notice from Busy, but my own request.

It's clear that Utopian is based on Busy source code and I'm glad that our work is helping other projects. However, I think that it's unhealthy for open-source ecosystem when people treat "open-source projects" as "noone's projects". Thing is, it's not like that.

When Utopian became its own project, it has been relicensed from MIT to GNU GPL license. At this time Busy copyrights has been purged from code. MIT license permits many things, but it doesn't make everyone owner of the code. You can't just take code from any project, put `Copyright Utopian` on it, and say it's your work. What really should be done to comply with MIT license (and in my opinion to comply with logic and respect to others work) is to license YOUR code under GNU GPL, but leave work that is not yours and you don't have rights to manage as-is.

Utopian is supposed to help open-source world. A lot of people start contributing to FOSS thanks to Utopian. That's why I think it's extremely important for Utopian to give a good example.

I'd be glad to see `Busy.LICENSE` file with original license with original copyright, and in README in License section explain how code is licensed:
```
Original source code licensed under MIT License. Copyright Busy
Utopian.io licensed under GNU Public License v3.0. Copyright Utopian.io
```

Thanks.

**Comment by azarus** [comment]
Hi. As far as i know utopian fullfills all the requirements of MIT. Now It is stated in the readme that the code has been forked from busy.  Also the MIT license allows "the rights to use, copy, modify, merge, publish,distribute, sublicense, and/or sell".
I dont see how does the utopian project breaches the MIT license? Can you providemore details please.
- Azarus

**Comment by ajayyy** [comment]
The license does say

> The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

**Comment by Sekhmet** [comment]
I have seen that Utopian.io team wonders if it makes sense to include original license, because they are basically different projects and changed most of the code.
1. You didn't change most of the code. Utopian.io is still at least 80% Busy code.
2. It doesn't' matter how much you changed. If there is one line from Busy code you still have to obey license.

What you do shows how little you really know (and care) about open-source.

**Comment by azarus** [comment]
@sekhmet we already had a discussion about this on the discord channel. There was probably a mistake by the devs when the project was quickly rushed and utopian copyright had to be added. It will be resolved asap we promise. 
Thanks for bringing this to our attention.

Also please keep your manners in place as it seems you have lost it between the comments....

**Comment by hernandev** [comment]
Hi, just passing by and noticed this issue.

As a reference, you guys can benchmark how easily one issue like this can escalate:

https://github.com/flyphp/flyframework/pull/1

**Comment by azarus** [comment]
I think we actually only have to add the correct copyright in the license file?

**Comment by ajayyy** [comment]
However you should leave a note about the changing licenses in the readme.

**Comment by diegopucci** [comment]
Done
