### ISSUE TITLE
Implement Moderation quality slider

### ISSUE THREAD

**Issue by diegopucci** [utopian-io/utopian.io#286]
On every contribution (not task requests) Moderators should fill a short questionnaire, made ad hoc for every contribution category. By filling the questionnaire a quality slider will be set. The questionnaire should make 80% max of the quality slider, while the remaining 20% can be set freely by the Moderator. The Utopian bot vote will then use the quality as a main factor for calculating the voting weight.

- Requires integration with API and edits on the API. Another developer will take care of the API changes.
- Moderators should never be able to approve or reject a contribution without first filling the questionnaire and consequently only after having set the quality slider.
- Related Task: Moderation should not also be able to reject or accept a contribution without having successfully added a comment before.
- Supervisors should be able to change the choices made by a moderator on the quality slider. For a moderator once submitted it is final.

**Comment by azarus** [comment]
@diegopucci I added the slider already now waiting for the backend api endpoint to be made.
![https://i.imgur.com/zsUujeT.png](https://i.imgur.com/zsUujeT.png)

The questionare can be stored in the backend.
The questions fill out the first 80% and the slide on the bottom the rest 20%, this is also configurable for each category. 

Can you elaborate how the Supervisors should be able to review the answers?

**Comment by azarus** [comment]
@diegopucci @wehmoen 
I just submitted a PR.

**ACs completed:**
- Requires integration with API and edits on the API. Another developer will take care of the API changes.
- Moderators should never be able to approve or reject a contribution without first filling the questionnaire and consequently only after having set the quality slider.
- Supervisors should be able to change the choices made by a moderator on the quality slider. For a moderator once submitted it is final.

**Comment by azarus** [comment]
@diegopucci @wehmoen 
PRs updated for backend and frontend both.

**Frontend**
https://github.com/utopian-io/utopian.io/pull/336 (Pending Review)

**Backend**
https://github.com/utopian-io/api.utopian.io/pull/90 (Merged)

**Comment by wehmoen** [comment]
@diegopucci the slider is implemented. and it works. can you provide the questions per category?

**Comment by diegopucci** [comment]
@wehmoen @azarus we have this document https://docs.google.com/document/d/1XKezGPZ8cwSQQGR1No7iBKkSkpyfChpdbk8S_Cvo-Kk. @azarus may you please review suggestions from supervisors there, accept or decline them and use those for the questionnaire?

**Comment by azarus** [comment]
@diegopucci 
#378 is now finished as far i see
#408 is awaitng review. It adds the new suggestions from supervsiors. 
The following categories have no questions only the 3 main ones.
- copywriting
- sub-projects
- ideas
- documentation
- blog

**Comment by wehmoen** [comment]
Talked to @azarus. The new questions should be implemented today :)

**Comment by wehmoen** [comment]
Hey any news about the questions?

**Comment by azarus** [comment]
@wehmoen pr is awaiting review

**Comment by wehmoen** [comment]
Thanks!
