### ISSUE TITLE
Moderation Cross-Editing

### ISSUE THREAD

**Issue by diegopucci** [utopian-io/utopian.io#287]
Moderators should be able to edit inline:

a. Repository
b. Categories, even from contributions to task requests.
c. Tags. 

- The API already supports cross-editing. Check update/ endpoint for posts.
- The functionality needs to be integrated in the contribution details, StoryFull component by integrating inline editing functionalities for mods.

**Comment by wehmoen** [comment]
Deadline: Feb. 16

**Comment by eastmaels** [comment]
Tasks to complete this issue:

1) inline edit for category
  A) change category
  B) broadcast to blockchain
2) inline edit proj. Repo
  A) change repo
  B) broadcast to blockchain
3) cross edit tags
  A) add tags
  B) remove tags
  C) broadcast to blockchain

**Comment by eastmaels** [comment]
I looked into a plugin - 'rieke' - but it throws an error about multiple react. Will post the error here later.
Will opt to pick-up what @ogbiyoyosky started.

**Comment by eastmaels** [comment]
Pushed initial change to my fork's branch: https://github.com/eastmaels/utopian.io/tree/feature/moderator-inline-edit-category

![category](https://user-images.githubusercontent.com/29425738/36340371-78d5bee8-1416-11e8-9ab3-94dafca992d1.png)

**Comment by diegopucci** [comment]
@eastmaels did u check the prs made by sirfreeman? Is there something we could reuse?

**Comment by eastmaels** [comment]
@diegopucci yes I checked his PR and am now reusing most of the codes. Just refactoring some and making the post update with the API.

**Comment by eastmaels** [comment]
Re-using codes from this PR:
https://github.com/utopian-io/utopian.io/pull/361

**Comment by wehmoen** [comment]
Merged in https://github.com/utopian-io/utopian.io/pull/416
