### ISSUE TITLE
Wallet From Busy.org

### ISSUE THREAD

**Issue by diegopucci** [utopian-io/utopian.io#289]
Integration of the wallet from Busy.org. Utopian is a originally a fork of Busy.org.

**Comment by Deviad** [comment]
I could help too with this.

**Comment by eastmaels** [comment]
These were the components identified that needed to be added:

1. Add Wallet Menu
 A. In Left Side bar - DONE
 B. In User Profile - NOT STARTED
2. Center Wallet
 a. Wallet Summary -DONE
 B. Account transfer history - DONE
3. Right sidebar
 A. Transfer function - DONE
 B. Market - DONE (without refresh function)
 C. Rewards - IN-PROGRESS
     1. Claim Rewards
     2. Current SBD and SP

**Comment by wehmoen** [comment]
![](https://files.slack.com/files-pri/T8Z9LSYAD-F96KUBPKQ/wallet-all.gif)

**Comment by eastmaels** [comment]
Thanks. Was just about to upload it.
