### ISSUE TITLE
Login Redirect

### ISSUE THREAD

**Issue by diegopucci** [utopian-io/utopian.io#291]
When logging in a modal should show up and explain briefly what SteemConnect is and redirect to SC within 3 seconds.

- Contents to write in the modal will be provided to you.

**Comment by stoodkev** [comment]
Hi, anything to change in those modals?

**Comment by stoodkev** [comment]
Merged in this pull request:
https://github.com/utopian-io/utopian.io/pull/269

Additionally, the modal was created for the landing page (yet to be merged):
https://github.com/utopian-io/join.utopian.io/pull/68
