### ISSUE TITLE
Help Center / Talk With Moderator Feature Suggestion(Utopian)

### ISSUE THREAD

**Issue by katteasis** [utopian-io/utopian.io#30]
**As I have already made my couple of contribution on utopian-io, and I’ve been regularly reading contributions from other members on the platform today I’ve come up a conclusion that we need a way to talk to moderator somehow before posting any contribution on the platform.**

# Problem Scenario (Why the platform Needs this?)
<br>
Well we all know this is a new platform and many new features, changes and rules will be updating in coming days. But at the moment I  feel we have only little resources about the platform, platform rules, and regulations and about the contribution patterns. Yes, we still don’t know how a ***Ideal Contribution*** should look like.
<br>
Yes, moderators are doing their job pretty well and they only approve any post as contribution after fulfilling the guidelines (which is very good), but still, it has there posted on steem blockchain already. I’m not liking this part so much, asking someone to edit and make changes publically on comments may make it/or make to feel it unreliable.( because I’ve seen more than five requests for edit on a single post) 
<br>
As I have been through most of the contribution, and the conversation between the moderator and poster it seems like there’s too much communication gap between moderators and contributors. Since the platform is new and everybody here is new and has less/or no experience with the platform so obliviously has less or no idea about how should we be posting the contribution.
So I think there should be someone for help at an instance. There should be someone with whom we can talk/ and ask for guidance while setting up our contributional post.This would only help us to produce better content.
<br>
# Possible Solutions.
<br>
My opinion here is, wouldn’t it be a better practice to have some way to review any contribution before posting it?
Or, any way to talk with a moderator would do a lot good.Or maybe a ***Help Center*** with frequently asked questions and an option to send a message to a mederator??

**This way a contributor can ask any confusion /questions regarding any contribution he’s going to make. This would help contributor to prepare and pre-proof his contribution writings.**
 
##  A. A Help Center.
<br>Yes a Help center with all asked/possible questions and answers, better explanations of keyphrases etc. And an option to send a message to support/moderator for instant reply would do a lot of help.<br>
![Need Help?.jpg](https://steemitimages.com/DQmZ1tfpL676japor9geJGbeq9HUvECnRnHg9EjL8zaHnzT/utopian1.jpg)
***Need Help?***
<br> <center>**OR**</center><br>
![Quick Help](https://steemitimages.com/DQmZpc1A2gmeb5Rqs8fM1ERsKimDUVXEqSAUx62ikRbTsqn/utopian2.jpg)
***Quick Help?***

## B. Live Chat with Moderator Option.
<br>Well this could be a better solution at the moment for us, the users. At the same time, I can understand that it might not be applicable for the platform in its initial stage.Yet I'm writing it as an option.<br>
![Online chat with moderator](https://steemitimages.com/DQmPMXoAWJ5fPQ7LkAo5xYdHSawToXjsUr4d6ztozHPH1GC/utopian.JPG)
***My example on live chat with moderator option.***
_____
<center>
### This will be very much helpful to the new user as well as the user who are here just for Utopian and never know about Steemit system.
____
<br>***I would like to read your opinion on this particular subject.***</center>
<br /><hr/><em>Open Source Contribution posted via <a href="https://utopian.io/utopian-io/@katteasis/help-center-talk-with-moderator-feature-suggestion-utopian">Utopian.io</a></em><hr/>

**Comment by azarus** [comment]
@katteasis Hi, there are multiple ways to learn how a contribution looks like, such a help center would dramatically reduce the available time of moderators and supervisors to review contributions. So this is not as good feature as it seems. 

I'd suggest you the following to do:
- Join our discord where you can get help from the community.
- Read other contributions and learn about how a contribution should look like.
- Post your contribution on utopian and learn from your mistakes. (Utopian isn't all about the rewards.)
