### ISSUE TITLE
Update rules for Visibility1/2

### ISSUE THREAD

**Issue by wehmoen** [utopian-io/utopian.io#312]
Visibility: Only ads on Search engines, Social media platforms, Thunderclap campaigns, posts on social media accounts with at least 10000 followers / potential audience will be accepted as valid contributions

**Comment by techslut** [comment]
Contributions to the visibility category to be accepted as valid contributions:

- Paid search engine ad placement
- Paid display ad placement
- Social media ad campaigns
- Thunderclap campaigns
- Posts to social media accounts with over 10,000 unique followers
