### ISSUE TITLE
Utopian-io: Giving to the announcements the place they deserve

### ISSUE THREAD

**Issue by stoodkev** [utopian-io/utopian.io#32]
![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509605014/hgdwjcimcshckdxlvg1c.png)

Few days ago, Utopian.io introduced the possibility for developers to make announcements. These announcements are directly linked to the Github folders and allow project authors to focus the help of the community where it most needed.

Although I see this new implementation as one of great value for the developer than I am, I think that those announcements cannot be seen clearly in the current version of Utopian. As far as I know, there is no direct method to see all the announcements on Utopian.

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509605386/kpmgxv51tqfbbycpcw5b.png)

The method I found is to search for a specific project first, for example utopian-io:

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509605507/diqk63yd5hluczifoqf2.png)

And then going to the annoucement tab:

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509605548/bczrrakzqqzntxlo6kgu.png)

I propose an implementation that would make more sense for the Thinkers, Translators, Developers, Bug hunters (etc.) out there. Adding a new tab similar to Contributions but for Announcements purposes only.

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509605704/hytibhz7k8iqlowhtu1c.png)

The menu item could be place directly above or under "Contributions" and open a panel similar to the Contributions, where its possible to filter request by Ideas, Bug, etc.

I believe that is doable since it would use the same layout and features than the already existing Contributions tab, and it would add an incentive for developers to use the announcement feature and for users to really help the development of the projects.

Hope this helps.

@stoodkev

<br /><hr/><em>Open Source Contribution posted via <a href="https://utopian.io/utopian-io/@stoodkev/utopian-io-giving-to-the-announcements-the-place-they-deserve">Utopian.io</a></em><hr/>

**Comment by azarus** [comment]
@stoodkev Hi i believe the Announcements feature had been replaced and is now known as Blog Posts feature.
