### ISSUE TITLE
Adding Cookie Policy to utopian.io

### ISSUE THREAD

**Issue by wehmoen** [utopian-io/utopian.io#321]
Add a the EU cookie notice to the landing page and make the cookie valid for *.utopian.io

**Comment by wehmoen** [comment]
Please also add a tooltip on the dev category icon to explain they have to sync if they did not and a way to show the synced github account on the contributions of the user

**Comment by diegopucci** [comment]
This page https://join.utopian.io/cookies/ needs to be removed since the plugin points already to the utopian.io cookies section

**Comment by wehmoen** [comment]
Done

**Comment by diegopucci** [comment]
@olo2552 @wehmoen moving this again as in-progress waiting for #381 to be fixed
