### ISSUE TITLE
Add a filter option on users profile

### ISSUE THREAD

**Issue by wehmoen** [utopian-io/utopian.io#325]
On user profile, in the contributions tab, add a way to filter contributions by status: accepted, pending, rejected. The filters should be usable by everyone looking at the profile.

**Comment by wehmoen** [comment]
Added Deadline: Feb. 16 2017

**Comment by diegopucci** [comment]
@Deviad @wehmoen moving this in-progress again waiting for #384 and #383

**Comment by wehmoen** [comment]
Done by @azarus while fixinf #411
