### ISSUE TITLE
Utopian signature is added right after the post text

### ISSUE THREAD

**Issue by espoem** [utopian-io/utopian.io#33]
It was pointed out that the Utopian signature is too close to my post text in one of my contributions. It was cause by adding the signature right after the text. It is inserted by Utopian to every submitted contribution.

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509607502/ohiktberik6vi4gxr0zi.png)

I ended that post with an ordered list. In Markdown, you need to separate the paragraphs with a blank new line. This did not happen and that's why the signature was added to the list.

`<hr/><em>Open Source Contribution posted via <a href="https://utopian.io/utopian-io/@espoem/missing-translation-of-page-requires-authentication">Utopian.io</a></em><hr/>`

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509607701/zmnb14jfj13c2hkl4t8e.png)

## Expected behaviour

The signature should be in its own paragraph.

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509607804/gg19mkopmhtsjcyniahg.png)

## Steps to reproduce

I will intentionally end the post with the list and with no new lines at the end.

1. Write new contribution
2. Put an ordered list at the end
3. Make sure there is no new line at the end<br /><hr/><em>Open Source Contribution posted via <a href="https://utopian.io/utopian-io/@espoem/utopian-signature-is-added-right-after-the-post-text">Utopian.io</a></em><hr/>

**Comment by azarus** [comment]
@espoem Hi, the issue had been already fixed, thank you.

**Current behavior:**
![](https://i.imgur.com/BIUEgMh.png)

@wehmoen issue can be closed
