### ISSUE TITLE
Development Rule Update

### ISSUE THREAD

**Issue by wehmoen** [utopian-io/utopian.io#339]
The linked Github repository must always contain code, a README and a license. [SOFT]. Split this rule. Github repository must always contain code should be HARD not SOFT

**Comment by espoem** [comment]
Is it really a good idea? What about projects / repositories that have only documentation, translation or another textual content but not the code. There are categories that are not always related to the code.

**Comment by diegopucci** [comment]
I am closing this task since it is related to #327
