### ISSUE TITLE
Tutorial Rule Update

### ISSUE THREAD

**Issue by wehmoen** [utopian-io/utopian.io#342]
We shouldn't allow simple Arduino tutorials. I stated this issue before, I'll state it again. There are tons of modules. Poeple can simply write one for each module. Of course, we should approve Arduino tutorials. But we shouldn't approve for example "how to get weight of an object with weight module". https://utopian.io/utopian-io/@drencolha/making-a-weight-scale-with-the-hx711-module-hx711-arduino-library-and-a-load-cell-tutorial

---

Keep it general. The problem is that users startet to contribute to this Software with way to easy contributions. If you have questions dm me :)

**Comment by techslut** [comment]
The current rule states: "Submission to this category must include technical instructions that explain and teach **non-trivial aspects** of an Open Source project."

These are trivial. So cannot be accepted. The end.
