### ISSUE TITLE
TOS and Privacy Acceptance: $500 worth of Steem + Utopian Upvotes

### ISSUE THREAD

**Issue by wehmoen** [utopian-io/utopian.io#343]
We also need to make sure the users should accept terms of service and privacy regulations if they have not done that yet and every time there is an update.

TOS and privacy policies will be given to you. They should show up in modals and the users should scroll down at the bottom of the text in order to click on "accept". Not accepting is not an option. Either the user accepts or leaves the site.

**Comment by olo2552** [comment]
Update of TOS, or update of any code change?

**Comment by diegopucci** [comment]
On top of what I wrote above contents of the modals should also be available on static pages utopian.io/tos utopian.io/privacy

**Comment by azarus** [comment]
PR for backend:
https://github.com/utopian-io/api.utopian.io/pull/97

**Comment by diegopucci** [comment]
@azarus wait for #376 for the final contents

**Comment by ogbiyoyosky** [comment]
O I

**Comment by diegopucci** [comment]
@azarus contents are ready. Please make a pr and reference it here. Push on develop branch for @wehmoen to test

**Comment by diegopucci** [comment]
@azarus on staging even if I accept tos and privacy, after reload it shows up anyways. Also the user can accept them without scrolling to the bottom.. @wehmoen this is not ready, please check back

**Comment by wehmoen** [comment]
@Azarus: I need to accept the tos and service agreement everytime i reload the page.
And I dont need to scroll down to accept it

**Comment by wehmoen** [comment]
Please fix this now!

**Comment by azarus** [comment]
@diegopucci PR ready
@wehmoen PR ready

**Comment by azarus** [comment]
@diegopucci 

> @azarus on staging even if I accept tos and privacy, after reload it shows up anyways. Also the user can accept them without scrolling to the bottom.. @wehmoen this is not ready, please check back

It is a database issue, there is some garbage in the users collection that needs to be cleaned or code added to the backend that checks if the data is in proper format.

**Comment by wehmoen** [comment]
Issue was solved and your pr was merged. Successfull tested your changes in staging environment.
