### ISSUE TITLE
Same titled different contributions showing same content

### ISSUE THREAD

**Issue by anilkilic** [utopian-io/utopian.io#349]
#### Expected behavior
Links should open releated pages.

#### Actual behavior
Different contribution links showing same page. 

#### How to reproduce
- Go to : https://utopian.io/project/ayobami99/steemstockphotos/github/111667980/all
- Click contribution from serkorkin
- Go back
- Click contribution from fulsketch

---
* Browser: MacOS High Sierra
* Operating system: Chrome & Safari

#### Recording Of The Bug
![zxc.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1518292487/fyndg09dxxhi9yr8kcnq.gif)
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@oups/same-titled-different-contributions-showing-same-content">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by wehmoen** [comment]
Deadline: Feb. 19th

**Comment by diegopucci** [comment]
@wehmoen @azarus is there a PR for this issue to reference?

**Comment by diegopucci** [comment]
@icaroharry @wehmoen is there any news regarding this issue?

**Comment by icaroharry** [comment]
Done: https://github.com/utopian-io/utopian.io/pull/394. Sorry the delay

**Comment by wehmoen** [comment]
Thanks
