### ISSUE TITLE
Quality Slider: Closes if mouse is released outside the modal

### ISSUE THREAD

**Issue by wehmoen** [utopian-io/utopian.io#378]
While using the slider i face the problem that if i release the mouse outside of the modal the modal closes.
related files: https://github.com/utopian-io/utopian.io/pull/336/files

**Comment by mktcode** [comment]
btw... this is actually a bug in ant design: https://ant.design/components/modal/

**Comment by wehmoen** [comment]
Well we should find a workaround. This is annoying and I think a lot of moderators will complain about it.

**Comment by mktcode** [comment]
quickest fix would be to disable "close on background click" if that's possible

**Comment by wehmoen** [comment]
@azarus can you check this?elear and I want to check all changes tomorrow

**Comment by mktcode** [comment]
I think it's `maskClosable={false}`... but wheeere...? :D
