### ISSUE TITLE
Wallet integration

### ISSUE THREAD

**Issue by wehmoen** [utopian-io/utopian.io#379]
I faced some problems with the wallet integration.

- there is no link to a users wallet in his profile
- If I try to access a users wallet the page is empty: https://staging.utopian.io/@mkt/wallet

**Comment by eastmaels** [comment]
Working on this now.

**Comment by eastmaels** [comment]
Fixed in PR #390 . 
Path to wallet from user profile is /@:name/transfers

**Comment by wehmoen** [comment]
I will test it now

**Comment by wehmoen** [comment]
Fixed!
