### ISSUE TITLE
Update Edited Post Button Too Far Away

### ISSUE THREAD

**Issue by ewuoso** [utopian-io/utopian.io#4]
![whatsapp image 2017-10-25 at 08 24 47](https://user-images.githubusercontent.com/33087808/31992620-4ccac714-b96a-11e7-80e1-68d046d2330a.jpeg)

i think the button should be immediately 
![whatsapp image 2017-10-25 at 08 25 04](https://user-images.githubusercontent.com/33087808/31992602-3f440e0c-b96a-11e7-81b9-613d457e89cc.jpeg)
below the box
#### How to reproduce

* Browser: 
* Operating system:

**Comment by azarus** [comment]
I think it is favorable for users to first review their posts then submit, i think the button is at a perfect location.
