### ISSUE TITLE
Fix bugs in development branch

### ISSUE THREAD

**Issue by wehmoen** [utopian-io/utopian.io#411]
### Privacy Policy/Terms of Service Modal:

The button "Scroll Down" can be clicked all the time and opens a popup "Scroll down to accept". Should be renamed to "Accept", disabled until scrolled down and all cancel actions should lead to logout.

After accepting, the popup still appears for a not so short moment when loading a pege.

![](https://i.imgur.com/SGPlVaQ.gif)

### Contributions/Task-Request Feed

Clicking a category tab adds the respective contributions to the bottom instead of switching the feed.

The same happens in the task request feed and even when switching from contributions to task requests.

![](https://i.imgur.com/50gRtLj.gif)

### Add Contribution

Clicking "+ Contribution" loads the respective page via JS and then makes a complete page refresh. Using the menu item in left sidebar works as expected.

![](https://i.imgur.com/wEIAaVL.gif)

### Review Feed

Review feed does not work.

![](https://i.imgur.com/TQ6C1Od.gif)

### Contribution Cross Editing

Changing the category removes the repository.

![](https://i.imgur.com/ORJSGbc.gif)

The SUB-PROJECT option must be removed, makes the contribution inaccessible.

![](https://i.imgur.com/EdJWxVJ.gif)

Tags and repository can't be changed in general. (Both were implemented before.)

##### General:
- Clicking the "+ Contribution" button does not work

##### Homepage:
- Clicking on Blog posts does not work
- Filtering the contributions does not work.

##### User Profile
- Clicking the logo on the upper left corner reloads the page and doesn't load the frontpage

**Comment by azarus** [comment]
hi @wehmoen i took care of: "Privacy Policy/Terms of Service Modal" pr is here: https://github.com/utopian-io/utopian.io/pull/412

**Comment by eastmaels** [comment]
Will prioritize fix for category cross inline editing.

**Comment by azarus** [comment]
@wehmoen @diegopucci pr https://github.com/utopian-io/utopian.io/pull/417

**Comment by azarus** [comment]
**Pushed more fixes for inline category and repo edition:**
https://github.com/utopian-io/utopian.io/pull/418

**Fixes:**
- UserBan caused errors in console 
- Category Edition
- Inline Repository Edit (Added debounce instead of key press(enter) search)
- removed sub-projects
- fixed invalid dom tags for moderation template selectors
- fixed repository edit messing up the layout

**Comment by wehmoen** [comment]
Awaiting review of changes and bugfixes by @diegopucci

**Comment by wehmoen** [comment]
Done
