### ISSUE TITLE
Logout on /write breaks page

### ISSUE THREAD

**Issue by wehmoen** [utopian-io/utopian.io#427]
If you try to logout on the "Add contribution" page the page reloads to a blank white site.

**Comment by wehmoen** [comment]
![image](https://user-images.githubusercontent.com/6608103/36666963-8dfdf7e0-1aec-11e8-9dd9-6058ab75ba9f.png)

**Comment by azarus** [comment]
Please ensure that NODE_ENV environment variable is in production.
Also the error was caused by the Help.js the PRs solves:
https://github.com/utopian-io/utopian.io/pull/437

**Comment by wehmoen** [comment]
Fixed. Logout now redirects to join.utopian.io
