### ISSUE TITLE
TOS and policy randomly shows up

### ISSUE THREAD

**Issue by wehmoen** [utopian-io/utopian.io#429]
SOmetimes the tos and privacy modal are shown even if the user has already accepted it.

**Comment by wehmoen** [comment]
Any progress in here? @azarus

**Comment by azarus** [comment]
@wehmoen this PR supposed to fix it: https://github.com/utopian-io/utopian.io/pull/445

**Comment by wehmoen** [comment]
Thanks! Its fixed now!
