### ISSUE TITLE
Category Inline Edit Missing Graphics Category

### ISSUE THREAD

**Issue by wehmoen** [utopian-io/utopian.io#430]
There is no graphics category on the category dropdown for inline edit.

**Comment by azarus** [comment]
@wehmoen  PR:
https://github.com/utopian-io/utopian.io/pull/438

**Comment by wehmoen** [comment]
Fixed with: https://github.com/utopian-io/utopian.io/commit/34f6bea8fe7fba9f6f45b58cf2202c8276250d6b
