### ISSUE TITLE
No redirect after creating a contribution

### ISSUE THREAD

**Issue by wehmoen** [utopian-io/utopian.io#434]
If a user creates a contribution and clicks "Post" the contribution is sucessfully created but the user is not redirected to his new contribution. Nothing happens.

TODO: Redirect the user to his new contribution after its posted.

I attached the console log
![image](https://user-images.githubusercontent.com/6608103/36668367-5e4df5fe-1af1-11e8-9870-3e7345a56a75.png)

**Comment by azarus** [comment]
@wehmoen it seems to be a server side issue, as the error says.

`failed to load resource: the server responded with a status of 500 (Internal Server Error)`

**Comment by azarus** [comment]
@wehmoen this PR supposed to fix it: https://github.com/utopian-io/utopian.io/pull/445

**Comment by wehmoen** [comment]
Fixed. Thanks!
