### ISSUE TITLE
Utopian.io people asking for proofreader rights on Open Food Facts in  Crowdin

### ISSUE THREAD

**Issue by teolemon** [utopian-io/utopian.io#442]
# The issue
I've seen dozen of people contacting us,  asking for proofreader rights on the translation project of Open Food Facts in Crowdin
https://crowdin.com/project/openfoodfacts
# Some examples
```In order to validate my work, the utopian platform asks me for proofread permission, so how do I get proofread permision for this project?```
```hello sir
I'm a translator from utopian.io
I want to translate your project in telugu language.
For my work to be accepted and evaluated in utopian I will need your permission of proof reading this project sir.
```
# The problem
Problem: we don't require being a proofreader to contribute, and granting proofreading rights means:
"Proofreader – does not have access to project settings, can translate and approve strings. Also, proofreader can accept/discard join requests and promote to proofreader or block translators."
https://support.crowdin.com/modifying-project-participants-roles/

# The solution ?
Can you just require translator status instead of proofreader ?

**Comment by diegopucci** [comment]
Contributors should have only proofreading capabalities for specific languages not global. This is to assure project owners only reward contributors that provide quality translations. It is up to the managers to decide wether to accept or not a request like that. Let me know if I can assist you with anyhing else

**Comment by teolemon** [comment]
@diegopucci I have finally found the rules at https://utopian.io/rules
- They really need to make a few translations before we can reward them with the power of promoting others to proofreading status.
- They really need to make a few translations before we can reward them with the power of blocking their competitors
