### ISSUE TITLE
/moderations route is accessible through a user profile.

### ISSUE THREAD

**Issue by anilkilic** [utopian-io/utopian.io#474]
#### Expected behavior
Page template shouldn't be accessible.

#### Actual behavior
Page template is accessible..

#### How to reproduce
- You can go to a user's profile and add `/moderations` to end of url.
ex. https://utopian.io/@azarus/moderations/
- and see tabs and datepicker
---
* Browser:  Safari
* Operating system: MacOS High Sierra

#### Recording Of The Bug
![Screen Shot 2018-03-06 at 02.04.47.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1520291475/nsm1a67ztmjw03jkcjsv.png)

    

<br /><hr/><em>**Rejected** on <a href="https://utopian.io/utopian-io/@oups/moderations-route-is-accessible-through-a-user-profile">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by wehmoen** [comment]
This is not a bug. The page shows no moderated posts for @azarus and that is 100% correct because he is not a moderator and did not moderate any contributions. The moderations menu point isnt there.
