### ISSUE TITLE
Moderated posts not visible for a moderator kit.andres

### ISSUE THREAD

**Issue by espoem** [utopian-io/utopian.io#475]
### Expected behaviour

Posts that were reviewed by kit.andres should be displayed in https://utopian.io/@kit.andres/moderations/

### Actual behaviour

Only one post is visible in the list.

![image](https://user-images.githubusercontent.com/16621517/37030920-ff2b612c-213c-11e8-8b62-2c7db8008bb6.png)

Kit.andres has reviewed 176 posts at the time of writing. https://api.utopian.io/api/posts?moderator=kit.andres

- Browser: Chrome 64
- OS: Windows 10

**Comment by wehmoen** [comment]
Assigned to: @decebal

**Comment by decebal** [comment]
https://github.com/utopian-io/utopian.io/pull/490

**Comment by wehmoen** [comment]
Fixed
