### ISSUE TITLE
Please add an easy way to opt-out from Utopian

### ISSUE THREAD

**Issue by vslavik** [utopian-io/utopian.io#480]
Hi,

lately, Poedit's [translation project](https://crowdin.com/project/poedit) has been spammed with weird requests that weren't happening in the past and that have some curiously common characteristics:

1. Use very vague "Poedit project" subject instead of describing the actual subject; I assume some tool of yours does that?
2. It's from people that never contributed to the project before, expressing how they'd like to contribute (but didn't: the project is open and people usually just sign up and *do* contribute).
3. They immediately, with zero track record in the project (and sometimes zero track record on Crowdin), ask for proofreader status. A responsible maintainer cannot grant that in this situation.
4. They don't even read the project's description, which explains that proofreading isn't used there.

Turns out they all have Utopian in common and they do it because they need to be proofreaders to receive a reward.

It would be great if it would be easily possible for projects (or entire GitHub accounts) to opt-out from being listed. 

At least *in my case*, you're not helping Open Source or rewarding the *actual* hard-working contributors, but are instead attracting newcomers motivated primarily by the money. This is consequently wasting maintainers' time in case of projects with governance incompatible with Utopian's requirements (proofreader status).

**Comment by diegopucci** [comment]
Hello. Thanks for getting in touch. We do understand there is an issue with newcomers willing only to get rewarded and we are working hard to ban them from our platform. Please provide the github repos you wish to be blacklisted. When a github repo is blacklisted, every contribution being submitted for that repo, will be immediately rejected by our moderators.

**Comment by diegopucci** [comment]
In the effort of showing our commitment to provide quality contributions, we just stopped entirely the translations category until a better solution can be implemented https://github.com/utopian-io/utopian.io/issues/480#issuecomment-371148776.

We want and will serve the Open Source cause as best as possible. Especially projects like Poedit are fundamental for us.

Thanks for your valuable feedback.
