### ISSUE TITLE
Declined comment template only fills input field on first click

### ISSUE THREAD

**Issue by tobias-g1** [utopian-io/utopian.io#486]
#### Expected behavior
The moderator comments should always fill the input field upon click no matter if I have clicked on that comment before. 

#### Actual behavior
If you click on a comment and then click on another comment and then click on the comment you clicked on first again that particular comment will not be entered into the comment field. 

#### How to reproduce
1. Moderator a post
2.  Decline the post and wait for the comment box to appear. 
3.  Take note that the default comment has filled the comment field. 
4. Click on the option for duplicate contribution
5. You will now see the comment field filled with the duplicate contribution template. 
6. Click on the default comment template
7.  The duplicate comment template will remain and the default comment template will not show. 

#### Environment 

* Browser: Version 64.0.3282.186 (Official Build) (64-bit)
* Operating system: MacOS HighSierra Version 10.13 (17A365)

#### Recording Of The Bug

The following image shows the issue:

![UtopianComments.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1520704246/vlmdqvnt9xxjozwa3gul.gif)
    
<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@tobias-g/declined-comment-template-only-fills-input-field-on-first-click">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by wehmoen** [comment]
I cant reproduce this. Furthermore you dont wrote which browser you use. You only gave me the version. I think its Chrome.

**Comment by tobias-g1** [comment]
Apologies for the browser, you're correct it was Chrome. That was a silly mistake on my account. 

I tested this again and still am able to replicate, not sure what's different about our environments.

**Comment by wehmoen** [comment]
Reopened due to new informations. I was now able to reproduce the bug after I saw a video.
