### ISSUE TITLE
GitHub sync show my private repo under my profile but not organisation repos

### ISSUE THREAD

**Issue by bonustrack** [utopian-io/utopian.io#5]
When i sync my GitHub account on Utopian and grant the GH organization "busyorg" there will be only my projects in my profile https://utopian.io/@fabien/projects including my private repository but not "busyorg" projects. This make me not able to connect busy.org repo. Also i would prefer to not show my private repositories like this.

**Comment by bonustrack** [comment]
![image](https://user-images.githubusercontent.com/16245250/32134172-91e89fe8-bc11-11e7-94bc-e236c91ad699.png)
Here is a screenshot of what i see, i will disable connection meanwhile.

**Comment by azarus** [comment]
I can confirm this had been fixed:
![](https://i.imgur.com/Ysjvj59.png)

Issue can be closed @wehmoen
