### ISSUE TITLE
Campaign Utopian.io on facebook

### ISSUE THREAD

**Issue by anaufalm** [utopian-io/utopian.io#501]
Hi, I will run a Utopian campaign on Facebook for visibility category on Utopian. 
Here is my link post on the page **Good News from Open Source** which I will promote. Hope you allow me to do this, and I will start the campaign, thank you. :)
https://www.facebook.com/364705867363678/photos/366855323815399

**Comment by wehmoen** [comment]
I will talk to our team and inform yout about our decission.

**Comment by anaufalm** [comment]
Okay, I'll waiting Dev :)

**Comment by wehmoen** [comment]
I talked to our team. We are currently not running any new campaigns until techslut comes back from vacation and builds a thorough marketing strategy for Q2/2018 for Utopian.
This means that this campaign is not eligable for the visibility category.

**Comment by anaufalm** [comment]
Okay, thanks
