### ISSUE TITLE
Matrix Chain Multiplication  by C code

### ISSUE THREAD

**Issue by agun-chowdhury** [utopian-io/utopian.io#508]
#### Components
@CodeBlocks is the software where we can implement this code for better result.

#### Proposal
This is the project about multiplication.For update this we can add  more logics like auto multiply,XOR gate task ,AND gate task etc.

#### Mockups / Examples
This is the C language code  for Matrix Chain Multiplication.If we implement this code  we can  get correct result easily.
In this code Matrix Ai  has dimention  p[i-1]*p[i], for  i=1.....n.
In line 12 number of multiplications  are zero (0) ,whene there is only one  matrix.
And  L  is chain length .it varies from length  2  to length  n.
In line  20 there  maximum  value was  assigned.

![Capturestm 1.JPG](https://res.cloudinary.com/hpiynhbhq/image/upload/v1521827054/fbhd1p1bmajatz79cl1q.jpg)

in line  27  if  number of multiplication found less  that  number  will be updated.
In  line 33 returning the final answer which is  M[1] [n].

![stm 2.JPG](https://res.cloudinary.com/hpiynhbhq/image/upload/v1521827065/jsztci6jix1chbdjdfxn.jpg)

#### Benefits
The benefits that we got from this simple project is we can calculate vast amount of data  without any complexity and in short time.Normally  we can calculate small matrix data orally or by hand.what  will happen when the matrix with data more than thousands row & column?so this code is the process  that we can calculate Matrix chain multiplication with at ease.

This is my first time  in this interesting  site  that i am trying  to contribute something.Hope this seems to be helpfull for  you all.
Thank You for  watch.Happy coding!!

**Comment by wehmoen** [comment]
Not related to this repo.
