### ISSUE TITLE
Request Permission Utopian Logo

### ISSUE THREAD

**Issue by anaufalm** [utopian-io/utopian.io#510]
Hello, I am a utopian contributor who contributed in the graphics category. Here I am designing a logo for one of the open source named [Utopmod Bot](https://utopian.io/utopian-io/@tolgahanuzun/need-a-logo-for-utopmod-telegram-bot). And I am inspired from the utopian logo and plan to use part of the utopian logo for Utopmod logo design.

I have read the [TOS](https://utopian.io/tos) page on the fifth point about Trademark, there said, _"...may not be copied, imitated or used, in whole or in part, without our prior written permission."_
Therefore, I would like to request permission to be able to partake of the utopian logo for the App logo. below I attach which part of the utopian logo I will use for the Utopmod logo. I will be happy if you give me permission. But if not, I will remove the logo. Thank you :)

![utopmod-proof](https://user-images.githubusercontent.com/35919168/37865258-583e2094-2f37-11e8-87d5-cf6734c9d086.png)

**Comment by wehmoen** [comment]
the utopian logo may only used by official utopian repositories and produts. Therefore we can‘t give you the permission to use our logo

**Comment by anaufalm** [comment]
Okay, I removed.
