### ISSUE TITLE
Report Bug = pending rewards schedule different between utopian.io with steemit.com

### ISSUE THREAD

**Issue by mohdhaekal** [utopian-io/utopian.io#512]
#### Expected behavior
The Utopian.io website should be able to show the appropriate pending rewards time like at steemit.com site.

#### Actual behavior
At the time we see Pending rewards time must be the same between in utopian.io and in steemit.com

#### How to reproduce
1. Go to utopian.io website and steemit.com site
2. Select the contribution elready upvote by utopian bot
3. Click on the pending rewards amount of the contribution
4. See the time difference of its reward

* google chrome version 65.0.3325.109
* operating system: android naugat 7.0

#### Recording Of The Bug
https://youtu.be/l86wyP7EKKw

**Comment by wehmoen** [comment]
This was reported several times before. We are already working on this :)
