### ISSUE TITLE
Bug Hunting -  Cannot upload picture on the Editor when filename has a space.

### ISSUE THREAD

**Issue by kizzbonez** [utopian-io/utopian.io#516]
#### Expected behavior
I am expecting that every time  I upload a picture on the Post editor ,  It will just upload it without an issue  even the file name has a space on it.

#### Actual behavior
If your picture has a space on its file name , it will be uploaded but you cannot see it on the preview of your post.

#### How to reproduce
- Make a contribution post.
- Upload a picture with a space on its name. example('my picture.png' or 'this isme.jpg').
- Then check if you can see it on the preview below your post editor. 

#### My Computer 
* Browser: Chrome
* Operating system: Windows 10 Pro x64

#### Recording Of The Bug
https://youtu.be/LhsNGUzI5_I

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@kizzbonez/bug-hunting-cannot-upload-picture-on-the-editor-when-filename-has-a-space">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by wehmoen** [comment]
This bug was fixed two days ago

**Comment by wehmoen** [comment]
And this bug report is wrong. You were absolutely aböe to upload files with a space. The real problem in here was the markdown parsing from the editor
