### ISSUE TITLE
Major posting bug, plus issues with profile picture, follower count

### ISSUE THREAD

**Issue by codename-littleboy** [utopian-io/utopian.io#55]
Utopian.io is having issues with connecting to steemconnect. The follower count and the profile avater is not loading. I removed cached files to see if the problem goes way but it is still there.

![bug](https://steemitimages.com/DQmVF7JiUSj8bZH7a2g7vAT8y3rsYL9uWdVgVzEJ24dhJRw/image.png)

When trying to post, utopian gives an error message saying that it can't connect to steem. The posts aren't getting saved in the draft section as stated in the error message.

![bug 2](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509740943/oxbwlkvbawvjkgehgc8j.png)

How to reproduce:

Browser version: Chrome 58.

Operating system: Windows 7.

[Note: I was working on this post yesterday when Utopian was down. I couldn't post it yesterday, so I saved it as draft in the steemit's editor. I am posting it now since everything is good again.]<br /><hr/><em>Open Source Contribution posted via <a href="https://utopian.io/utopian-io/@littleboy/major-posting-bug-plus-issues-with-profile-picture-follower-count">Utopian.io</a></em><hr/>

**Comment by azarus** [comment]
@codename-littleboy thank you for your help, It was most likely a temporary server outage of either utopian.io, / steem api or steemconnect.

@wehmoen I think it is a duplicate or it had been fixed, can you evaluate this issue thank you.

**Comment by wehmoen** [comment]
This was caused by serverproblems on steemit.com
