### ISSUE TITLE
Change FLAGGED status to HIDDEN

### ISSUE THREAD

**Issue by espoem** [utopian-io/utopian.io#56]
#### Expected behavior

It should say HIDDEN instead of FLAGGED.

#### Actual behavior

If a contribution is hidden, it says "FLAGGED by". This wording is confusing since the function button say "hide forever". To flag also means to downvote on Steemit, which is not the case of this function.

![image](https://user-images.githubusercontent.com/16621517/32404641-a922f626-c153-11e7-97a4-fdacef6201c4.png)

![image](https://user-images.githubusercontent.com/16621517/32404646-e167ef6e-c153-11e7-8b5a-47961f71970b.png)

#### How to reproduce

1. Open a contribution that hasn't been review yet
2. Hide it

**Comment by eastmaels** [comment]
For PR Merge.
