### ISSUE TITLE
Replies Menu Is Empty and Not Working

### ISSUE THREAD

**Issue by arietm** [utopian-io/utopian.io#57]
Hello everyone
Today I am looking for some bugs in utopian to be able to report, this bug hunt is indispensable for the development of an opensource in the future. and I find bugs that have not been previously reported.

I want to report about the reply feature in utopian.io, I find the reply feature is very difficult and apparently on the list when we click draft. I feel this feature is very hidden and hard to find, and now I just realized it.

But when I click on REPLIES it still does not exist anything and I feel this bug should be resolved, because the feature is very we need to know the message of reply from others.

You can see it like the picture below. or you may try with this link https://utopian.io/replies

![replies.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509795222/vhpxpunnnirikodlnlyp.png)

As you can see in the picture above, that when we click on replies we will be taken to the contribution list page and I think it is a bug that should be resolved quickly. and I also recommend that the reply message feature be placed in the profile page section of the contributory menu list, project, followers, following. so we can easily find the reply menu and we can quickly reply to messages from others.

Hopefully this report can be useful and can be improved immediately so that utopian users are easier to use utopian in finding the message reply.

<center>Author : @arie.steem
Adsactly & Utopian-io</center>

Communite With Us In
Discord ADSactly :https://discordapp.com/invite/6jAXNuu
Discord utopian.io :https://discord.gg/72bPmxk
<br /><hr/><em>Open Source Contribution posted via <a href="https://utopian.io/utopian-io/@arie.steem/replies-menu-is-empty-and-not-working">Utopian.io</a></em><hr/>

**Comment by azarus** [comment]
@arietm thanks for opening the issue.

As far as i understand the task here would be to implement the replies feature from busy.org.

**To find the replies page go to:**
https://utopian.io/settings
It redirects to a steemit.com page. (This is probably a temporary workaround)

**Currently it is Broken:**
https://utopian.io/replies

@wehmoen could you please evaulate wether the issue can be closed or needs to be added to the feature requests?

**Comment by wehmoen** [comment]
Fixed with external  link
