### ISSUE TITLE
Utopian can't find my project

### ISSUE THREAD

**Issue by JefPatat** [utopian-io/utopian.io#64]
When adding a contribution to Utopian one has to refer to the github project so that the work done can be verified. I am trying to add a new contribution for the OpenV project which is found here: https://github.com/openv/openv

OpenV is a project to interface with Viessmann domestic heaters. The wiki is a collection of all information about every aspect of this interfacing. Software, hardware, protocol, ... This project does not have code but uses github for the wiki alone at the moment. The project was moved because the previous host started charging too much. The old wiki is still available but no longer editable: https://openv.wikispaces.com

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1510148180/tjnqgl1pbi6kzvgsyi7i.png)

When I try to select a Github project I can't find this project. I get quite a few suggestions for other projects containing 'openv' but not the project I need.

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1510148437/lh6w7tgjjj8wssqnmvae.png)

I tried entering several combinations such as 'https://github.com/openv/openv', 'openv', 'openv/openv' but the project is never found.

<br /><hr/><em>Open Source Contribution posted via <a href="https://utopian.io/utopian-io/@jefpatat/utopian-can-t-find-my-project">Utopian.io</a></em><hr/>

**Comment by codingdefined** [comment]
Its Fixed

**Comment by sirrius-a-b** [comment]
I can confirm, this is fixed, it can be closed.

**Comment by JefPatat** [comment]
entering 'openv' doesn't list the project mentioned above for me
