### ISSUE TITLE
Tooltip remains after Click in Utopian-io

### ISSUE THREAD

**Issue by codingdefined** [utopian-io/utopian.io#65]
In the My Profile of Utopian-io, when I click the (...), it opens up two options Support and Block this user as shown below.

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1510139950/oijhnltaqpxuybrmgkhj.png)

When I click on Support it opens up, the transfer funds window, but the option of Support and Block this user is still visible

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1510140109/vud1fync2vpzxk9vjw8n.png)

When you click anywhere in the transfer funds window, the option of Support and Blocks goes away.

### Expected Behaviour

When we click on the support option only Transfer Funds window should be visible and not the option of Support and Block this user. 

### Steps To Reproduce

1. Open My Profile in Utopian-io
2. Click on (...) button which is beside Edit profile button
3. Then Click on Support Option

<br /><hr/><em>Open Source Contribution posted via <a href="https://utopian.io/utopian-io/@codingdefined/tooltip-remains-after-click-in-utopian-io">Utopian.io</a></em><hr/>

**Comment by eastmaels** [comment]
Will work on this.
