### ISSUE TITLE
Allow closed PR to be selected when writing a post

### ISSUE THREAD

**Issue by gregory-latinier** [utopian-io/utopian.io#73]
Hi,
I recently wanted to comment and explained a little what has been done on [Steemconnect](https://github.com/steemit/steemconnect) but I was surprised that I couldn't choose to select a closed PR.

This is kind of sad because I usually talk about something when it's done and completed especially for development.

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1510332283/ydcspmbbhgayimcsijuj.png)

As you can see above only the PR pending a review are shown :(

What do you think ? Because I really want to show you some good stuffs on steemconnect !!!

Greg

<br /><hr/><em>Open Source Contribution posted via <a href="https://utopian.io/utopian-io/@gregory.latinier/allow-closed-pr-to-be-selected-when-writing-a-post">Utopian.io</a></em><hr/>

**Comment by codingdefined** [comment]
@diegopucci Should we want this feature, as because it will add 100s of PR if you have done a lot of changes and then you need to search the appropriate PR.

**Comment by azarus** [comment]
@gregory-latinier Hey, the expected behavior is to show only approved PR's. Which i believe this is how it currently works.
