### ISSUE TITLE
Projects list displays private projects

### ISSUE THREAD

**Issue by inertia186** [utopian-io/utopian.io#75]
I have private projects that are being listed in `/projects` tab of my profile on utopian.io.  This seems inappropriate.

[![](https://cl.ly/1p2K2H050W2H/Image%202017-11-10%20at%2010.47.38%20PM.png)](https://cl.ly/1p2K2H050W2H)

<br /><hr/><em>Open Source Contribution posted via <a href="https://utopian.io/utopian-io/@inertia/projects-list-displays-private-projects">Utopian.io</a></em><hr/>

**Comment by codingdefined** [comment]
Its fixed now

**Comment by inertia186** [comment]
Confirmed.  Thank you.
