### ISSUE TITLE
Please lower github app permissions

### ISSUE THREAD

**Issue by piem** [utopian-io/utopian.io#77]
hello there,

When trying to sync with github, the app currently request read & write permissions to the following:
 
 - Private email addresses
 - Private profile information
 - Followers
 - Code
 - Issues
 - Pull requests
 - Wikis
 - Settings
 - Webhooks and services
 - Deploy keys
 - Collaboration invites
 - Gists

Please update the permissions to keep only the required one. I would suggest starting from a bare minimum, like read-only repository contents and issues.

I would really like to give it a go, but write access to my repos is a no-go for me.

Cheers, piem

**Comment by NeHoMaR** [comment]
Just the private email was enough for me to not doing the sync.

**Comment by piem** [comment]
hi @diegopucci are you reading this?

**Comment by wackou** [comment]
+1, it's a dealbreaker for me too
