### ISSUE TITLE
Utopian.io bug in the category nevigation arrow

### ISSUE THREAD

**Issue by littleboy0k** [utopian-io/utopian.io#85]
In the main site of Utopian.io, there are lots of categories that sort contributions based on their type. The categories are "All", "Ideas", "Development" etc. Since there are too many categories then that can fit in the screen size, further categories need to be accessed by clicking on the two arrow buttons shown in the below image.

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1510662295/nqjebyekvwguntaf8beh.png)

Today, when I clicked on one of those arrows, it didn't work the way it should. I have added a gif image showing this below.

![1.2 Utopian category bug 14.11.2017.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1510663356/ybrelstgjxubybbwhodd.gif)

The gif image is made of two different gifs. I run the test twich to see if it improves or not. But no improvements were seen.

Actual result:

The category arrow keys not functioning properly. Not able to view some categories due to this bug.

Expected result:

The arrow keys function properly.

How to reproduce:

1. Visit Utopian.io.
2. Click on the arrow like shown in the gif image.

OS: Windows 7
Browser: Chrome 58
Javascript: Enabled
Flash: Enabled

<br /><hr/><em>Open Source Contribution posted via <a href="https://utopian.io/utopian-io/@littleboy/utopian-io-bug-in-the-category-nevigation-arrow">Utopian.io</a></em><hr/>

**Comment by sirrius-a-b** [comment]
I was not able to reproduce this bug. Chrome 62/Linux Mint 18.1

**Comment by azarus** [comment]
@wehmoen issue can be closed as the bug can't be reproduced (it was likely not existent).

**Comment by littleboy0k** [comment]
@azarus The bug indeed existed when I posted this. Now that Utopian's legacy UI has been dropped, I am closing the issue.

**Comment by azarus** [comment]
@littleboy0k thanks but i am not longer contributing to the project so you don't have to mention me. :)
As i am busy with other stuff and i really have no idea what this bug was about :)
