### ISSUE TITLE
Bug when navigating to a project page

### ISSUE THREAD

**Issue by nathpaiement** [utopian-io/utopian.io#96]
# The bug:
![linkError.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1510951278/ywtwci7y0mwpcxwpifdi.png)

When wanting to navigate to a project page, the first click doesn't register (no loading of the project's feed), but the address bar changes to the right destination. Only the second click (doesn't even have to be on the same contribution) registers and loads the feed of the clicked project.

This is what the browser console spew out from the first unsuccessful click:
![2017-11-17_22-03-39.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1510952753/tykgmmprnqb2ogcekglf.png)

Browser: Chrome 62.0.3202.94 (Official Build) (64-bit) on Windows 10

---

### Getting closer to the source of the bug
After playing in the browser console and putting some breakpoints, I noticed some things that might help solving this bug.

*Stepping through the `renderContributions()` function in src/feed/SubFeed.js:*

![linkErrorConsole.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1510952052/qevxvfxdsgx33zqztbuf.png)

1. me wanting to open the "OpenYGO" project page
2. what are WordPress posts doing here? I know that was the last project page I visited, but I returned to the main feed before doing step 1... weird
3. the filter function seems to be rejecting the WordPress posts as it should

I think when clicking for the first time on a link to the project page, the script tries to load a cached list of contributions, from whichever project page one last visited. Now since the cached contributions don't belong to the requested project, `renderContributions()` returns empty and the feed doesn't change. Only on the second click, that the script seems to work.

Now I'm not familiar with the Utopian/Busy code, so I'd rather leave the bug fixing to more able devs :)

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@callmetoxy/bug-when-navigating-to-a-project-page">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by codingdefined** [comment]
I will be working on this Issue
